### PR TITLE
README.md: Cleanup documentation

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
Still WIP, I haven't tested it on a VM yet and still haven't gotten a slave working.

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
@kaspar030 I did say something about the directory structure.  I don't think this is actually currently how it is implemented but maybe it would be good to do this.  I really don't like this `murdock/murdock/` stuff.

**Comment by kaspar030** [comment]
Please squash, I think this can just be merged!

**Comment by kaspar030** [comment]
> Still WIP, I haven't tested it on a VM yet and still haven't gotten a slave working.

I mean, the whole repo is experimental, so I think we can move a bit faster here.

**Comment by MrKevinWeiss** [comment]
Done!

**Comment by kaspar030** [comment]
Thanks!

**Pull request merged**
